name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other environments like macOS or Windows if necessary

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Install Catch2 dependencies
    - name: Install Catch2
      run: sudo apt-get install -y catch2

    # Install ninja generator
    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    # Build Project
    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        generator: Ninja
        cxx-compiler: g++
        build-dir: out/build/gcc

    # Run Tests
    - name: Test Project
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: out/build/gcc

