name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other environments like macOS or Windows if necessary

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Install Catch2 dependencies
    - name: Install Catch2
      run: sudo apt-get install -y catch2

    # Install GCC
    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest

    # Install ninja generator
    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    # Build Project
    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        generator: Ninja
        cxx-compiler: g++
        build-dir: out/build/gcc

    # Run the tests using CTest
    - name: Run Tests
      run: |
        cd out/build/gcc
        ctest --output-on-failure
